### ISSUE TITLE
why new edtion xmr-stak hashrate so low？

### ISSUE THREAD

**Issue by xingsj** [nioroso-x3/xmr-stak#1]
Please provide as much as possible information to reproduce the issue.

  - Type of the CPU.   : ibm power 8 8 core

pre edition hashrate :1750 h/s
 now    :   860 h/s

**Comment by avollmerhaus** [comment]
My guess is that [this](https://github.com/madscientist159/xmrig#power-performance-comparison-cnv7-to-cnv8) applies to Power8 as well

**Comment by nioroso-x3** [comment]
Power8 sucks at square root and division.

**Comment by madscientist159** [comment]
POWER9 is doing OK though, at least with a properly tuned miner.  See https://github.com/madscientist159/xmrig/issues/2 for numbers.

In comparison, POWER8 is now almost 5 years old.  The CNv8 fork also knocked out GPUs and x86 CPUs that are of that vintage; this "refreshing" of mining hardware was semi-intentional as far as I can tell (if a little wasteful).
